import VideogameAssetRoundedIcon from "@mui/icons-material/VideogameAssetRounded";
import Xbox from "./images/xbsxs.png"

const Data = [
  {
    id: 1,
    abbreviation: "MO",
    gen: "1",
    manufacture: "Magnavox",
    system: "Magnavox Odyssey",
    units: "330K",
    describe: "the first home video game console, is released.",
    year: "1972",
    discontinued: "1975",
    price: "$99",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/0f/Magnavox-Odyssey-Console-Set.png",
    game1: "Astrosmash",
    game2: "Tron: Deadly Discs",
    game3: "Advanced Dungeons & Dragons",
    game4: "Lock 'n' Chase",
    game5: "BurgerTime",
  },
  {
    id: 2,
    abbreviation: "AHP",
    gen: "1",
    manufacture: "Atari",
    system: "Home Pong",
    units: "1M",
    describe: "the first popular home console, is released.",
    year: "1975",
    discontinued: "1978",
    price: "$99",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/08/TeleGames-Atari-Pong.png",
    game1: "",
    game2: "",
    game3: "",
    game4: "",
    game5: "",
  },
  {
    id: 3,
    abbreviation: "A26",
    gen: "1",
    manufacture: "Atari",
    system: "Atari 2600",
    units: "30M",
    describe:
      "is released and becomes the first major success of home video gaming",
    year: "1977",
    discontinued: "1992",
    price: "£199",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Atari-2600-Wood-4Sw-Set.png/440px-Atari-2600-Wood-4Sw-Set.png",
    game1: "Pac-Man",
    game2: "Space Invaders",
    game3: "Asteroids",
    game4: "Pitfall",
    game5: "Adventure",
  },
  {
    id: 4,
    abbreviation: "CV",
    gen: "2",
    manufacture: "Coleco",
    system: "ColecoVision",
    units: "2M",
    discontinued: "1985",
    price: "$175",
    describe:
      "is released and becomes the first major success of home video gaming",
    year: "1982",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/2a/ColecoVision-wController-L.png",
    game1: "Donkey Kong",
    game2: "Zaxxon",
    game3: "Pitfall!",
    game4: "Frogger",
    game5: "Donkey Kong Jr",
  },
  {
    id: 5,
    abbreviation: "MI",
    gen: "2",
    manufacture: "Magnavox",
    system: "Intellivision",
    units: "3M",
    describe:
      "is released and becomes the first major success of home video gaming",
    year: "1982",
    discontinued: "1990",
    price: "$299",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/fc/Intellivision-Console-Set.png",
    game1: "Table Tennis",
    game2: "Ski",
    game3: "Football",
    game4: "Volleyball",
    game5: "Haunted House",
  },
  {
    id: 6,
    abbreviation: "A52",
    gen: "2",
    manufacture: "Atari",
    system: "Atari 5200",
    units: "1M",
    describe:
      "is released and becomes the first major success of home video gaming",
    year: "1982",
    discontinued: "1984",
    price: "$269",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/5f/Atari-5200-Console-Set.png",
    game1: "Pac-Man",
    game2: "Missile Command",
    game3: "Super Breakout",
    game4: "Centipede",
    game5: "Galaxian",
  },
  {
    id: 7,
    abbreviation: "NES",
    gen: "3",
    manufacture: "Nintendo",
    system: "Nintendo Entertainment System",
    units: "61M",
    describe:
      "Nintendo releases the Nintendo Entertainment System (NES) in North America, reviving the video game industry and starting the third generation of home consoles.",
    year: "1985",
    discontinued: "1995",
    price: "£125",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b2/NES-Console-Set.png",
    game1: "Super Mario Bros",
    game2: "The Legend of Zelda",
    game3: "Metroid",
    game4: "Castlevania",
    game5: "Mega Man",
  },
  {
    id: 8,
    abbreviation: "SG",
    gen: "3",
    manufacture: "Sega",
    system: "Sega Genesis",
    units: "30M",
    describe:
      "Sega releases the Sega Genesis, starting the fourth generation of home consoles",
    year: "1988",
    discontinued: "1997",
    price: "£189",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/26/Sega-Genesis-Mod1-Set.png",
    game1: "Sonic the Hedgehog",
    game2: "Phantasy Star IV",
    game3: "Street Fighter II",
    game4: "Mortal Kombat",
    game5: "Shining Force II",
  },
  {
    id: 9,
    abbreviation: "SNES",
    gen: "4",
    manufacture: "Nintendo",
    units: "49M",
    system: "Super Nintendo Entertainment System",
    describe:
      " Super Nintendo Entertainment System (SNES) is released, competing with Sega Genesis.",
    year: "1990",
    discontinued: "1999",
    price: "£150",
    icon: <VideogameAssetRoundedIcon />,
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/SNES_US.png",
    game1: "Super Mario World",
    game2: "The Legend of Zelda: A Link to the Past",
    game3: "Super Metroid",
    game4: "Final Fantasy VI",
    game5: "Donkey Kong Country",
  },
  {
    id: 10,
    abbreviation: "AJ",
    gen: "4",
    manufacture: "Atari",
    system: "Atari Jaguar",
    units: "250K",
    describe:
      "Atari releases the Atari Jaguar, which fails to gain significant market share.",
    year: "1993",
    discontinued: "1996",
    price: "£249",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/90/Atari-Jaguar-Console-Set.png",
    game1: "Alien vs. Predator",
    game2: "Doom",
    game3: "Wolfenstein 3D",
    game4: "Tempest 2000",
    game5: "Iron Soldier",
  },
  {
    id: 11,
    abbreviation: "PS1",
    gen: "5",
    manufacture: "Sony",
    system: "PlayStation",
    units: "102M",
    describe:
      "Sony enters the console market with the release of the PlayStation, starting the fifth generation of home consoles.",
    year: "1994",
    discontinued: "2006",
    price: "£299",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/95/PSX-Console-wController.png",
    game1: "Final Fantasy VII",
    game2: "Metal Gear Solid",
    game3: "Resident Evil",
    game4: "Crash Bandicoot",
    game5: "Tomb Raider",
  },
  {
    id: 12,
    abbreviation: "SS",
    gen: "5",
    manufacture: "Sega",
    system: "Sega Saturn",
    units: "9M",
    describe:
      "Sega releases the Sega Saturn, which fails to compete with the PlayStation.",
    year: "1993",
    discontinued: "1998",
    price: "",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Sega-Saturn-Console-Set-Mk1.png/500px-Sega-Saturn-Console-Set-Mk1.png",
    game1: "Virtua Fighter 2",
    game2: "Virtua Cop 2",
    game3: "Sega Rally Championship",
    game4: "Panzer Dragoon II Zwei",
    game5: "Sonic Jam",
  },
  {
    id: 13,
    abbreviation: "N64",
    gen: "5",
    manufacture: "Nintendo",
    system: "Nintendo 64",
    units: "33M",
    describe:
      "Nintendo releases the Nintendo 64, which features 3D graphics and becomes a popular console.",
    year: "1996",
    discontinued: "2002",
    price: "£250",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/N64-Console-Set.png/440px-N64-Console-Set.png",
    game1: "Super Mario 64",
    game2: "The Legend of Zelda: Ocarina of Time",
    game3: "GoldenEye 007",
    game4: "Mario Kart 64",
    game5: "Donkey Kong 64",
  },
  {
    id: 14,
    abbreviation: "APIP",
    gen: "5",
    manufacture: "Apple",
    system: "Pippin",
    units: "44k",
    describe:
      "The console was based on a modified version of the Macintosh operating system and was intended to provide an affordable alternative to more expensive gaming consoles.",
    year: "1996",
    discontinued: "1997",
    price: "$599",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/2f/Pippin-Atmark-Console-Set.png",
    game1: "Super Marathon",
    game2: "Dragon's Lair",
    game3: "Gadget: Invention Travel & Adventure",
    game4: "Monty Python's Complete Waste of Time",
    game5: "Mr. Potato Head Saves Veggie Valley",
  },
  {
    id: 15,
    abbreviation: "SD",
    gen: "6",
    manufacture: "Sega",
    system: "Sega Dreamcast",
    units: "9M",
    describe:
      " The Dreamcast was the first 128-bit console and boasted impressive hardware capabilities at the time of its release, including a built-in modem for online gaming.",
    year: "1998",
    discontinued: "2001",
    price: "£199",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/a0/Sega-dreamcast-set.png",
    game1: "Virtua Fighter 2",
    game2: "Virtua Cop 2",
    game3: "Sega Rally Championship",
    game4: "Panzer Dragoon II Zwei",
    game5: "Sonic Jam",
  },
  {
    id: 16,
    abbreviation: "PS2",
    gen: "6",
    manufacture: "Sony",
    system: "PlayStation 2",
    units: "155M",
    describe:
      "Sony releases the PlayStation 2, starting the sixth generation of home consoles.Sony PlayStation 2, a powerful console that became the best-selling video game console of all time, is released",
    year: "2000",
    discontinued: "2013",
    price: "£299",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/PlayStation_2.png/731px-PlayStation_2.png?20100912003948",
    game1: "Grand Theft Auto: San Andreas",
    game2: "God of War",
    game3: "Kingdom Hearts",
    game4: "Metal Gear Solid 2: Sons of Liberty",
    game5: "Shadow of the Colossus",
  },
  {
    id: 17,
    abbreviation: "NGC",
    gen: "6",
    manufacture: "Nintendo",
    system: "Nintendo GameCube",
    units: "21M",
    describe:
      "Nintendo GameCube, a compact console with improved graphics and sound, is released",
    year: "2001",
    discontinued: "2007",
    price: "£129",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/GameCube-Console-Set.png/440px-GameCube-Console-Set.png",
    game1: "Super Smash Bros. Melee",
    game2: "The Legend of Zelda: The Wind Waker",
    game3: "Metroid Prime",
    game4: "Resident Evil 4",
    game5: "Super Mario Sunshine",
  },
  {
    id: 18,
    abbreviation: "XB",
    gen: "6",
    manufacture: "Microsoft",
    system: "Xbox",
    units: "24M",
    describe:
      "Microsoft Xbox, a powerful console with an emphasis on online gaming, is released",
    year: "2001",
    discontinued: "2009",
    price: "£299",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c2/Xbox-Console-Set.png",
    game1: "Halo: Combat Evolved",
    game2: "Fable",
    game3: "Star Wars: Knights of the Old Republic",
    game4: "The Elder Scrolls III: Morrowind",
    game5: "Project Gotham Racing",
  },
  {
    id: 19,
    abbreviation: "XB360",
    gen: "7",
    manufacture: "Microsoft",
    system: "Xbox 360",
    units: "84M",
    describe:
      "Xbox 360, a more powerful and refined version of the original Xbox, is released and becomes a major success",
    year: "2005",
    discontinued: "2016",
    price: "£279",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/a8/Xbox-360-Pro-wController.png",
    game1: "Gears of War",
    game2: "BioShock",
    game3: "Mass Effect",
    game4: "Halo 3",
    game5: "Call of Duty 4: Modern Warfare",
  },
  {
    id: 20,
    abbreviation: "Wii",
    gen: "7",
    manufacture: "Nintendo",
    system: "Nintendo Wii",
    units: "102M",
    describe:
      "Nintendo Wii, a console that emphasized motion controls and accessibility, is released and becomes a massive success",
    year: "2006",
    discontinued: "2013",
    price: "£179",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Wii-Console.png/440px-Wii-Console.png",
    game1: "Super Mario Galaxy",
    game2: "The Legend of Zelda: Twilight Princess",
    game3: "Wii Sports",
    game4: "New Super Mario Bros. Wii",
    game5: "Mario Kart Wii",
  },
  {
    id: 21,
    abbreviation: "PS3",
    gen: "7",
    manufacture: "Sony",
    system: "PlayStation 3",
    units: "87M",
    describe:
      "The PlayStation 3 was released in 2006 and sold around 87Mion units worldwide.",
    year: "2006",
    discontinued: "2017",
    price: "£425-£599",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/91/Ps3-fat-console.png",
    game1: "The Last of Us",
    game2: "Uncharted 2: Among Thieves",
    game3: "Metal Gear Solid 4: Guns of the Patriots",
    game4: "LittleBigPlanet",
    game5: "Demon's Souls",
  },
  {
    id: 22,
    abbreviation: "WiiU",
    gen: "8",
    manufacture: "Nintendo",
    system: "Nintendo Wii U",
    units: "13M",
    describe:
      "Nintendo releases the Wii U, a console with a touchscreen gamepad.",
    year: "2012",
    discontinued: "2017",
    price: "£249-£299",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Wii_U_Console_and_Gamepad.png/440px-Wii_U_Console_and_Gamepad.png",
    game1: "Mario Kart 8",
    game2: "New Super Mario Bros. U",
    game3: "Super Mario 3D World",
    game4: "Nintendo Land",
    game5: "Super Smash Bros. for Wii U",
  },
  {
    id: 23,
    abbreviation: "XB1",
    gen: "8",
    manufacture: "Microsoft",
    system: "Xbox One",
    units: "51M",
    describe:
      "The Xbox One was released in 2013 a few weeks before the PlayStation 4 to become the first eight genration home console.",
    year: "2013",
    discontinued: "Present",
    price: "£429",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/2b/Microsoft-Xbox-One-Console-wKinect.png",
    game1: "Halo 5: Guardians",
    game2: "Gears of War 4",
    game3: "Forza Horizon 3",
    game4: "Cuphead",
    game5: "Titanfall 2",
  },
  {
    id: 24,
    abbreviation: "PS4",
    gen: "8",
    manufacture: "Sony",
    system: "PlayStation 4",
    units: "117M",
    describe:
      "Sony releases the PlayStation 4, starting a new genration in gaming taking the world by storm",
    year: "2013",
    discontinued: "Present",
    price: "£349",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/a8/Sony-PlayStation-4-PS4-DualShock-4.png",
    game1: "God of War",
    game2: "The Last of Us Part II",
    game3: "Spider-Man",
    game4: "Horizon Zero Dawn",
    game5: "Bloodborne",
  },
  {
    id: 25,
    abbreviation: "NS",
    gen: "9",
    manufacture: "Nintendo",
    system: "Nintendo Switch",
    units: "122M",
    describe:
      "Nintendo Switch, a hybrid console that can be played both on a TV and as a handheld, is released and becomes a major success",
    year: "2017",
    discontinued: "Present",
    price: "£279",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://assets.nintendo.com/image/upload/f_auto/q_auto/dpr_2.0/c_scale,w_400/Dev/nin-component/dual-hardware/split-cta-system",
    game1: "The Legend of Zelda: Breath of the Wild",
    game2: "Super Mario Odyssey",
    game3: "Super Smash Bros. Ultimate",
    game4: "Animal Crossing: New Horizons",
    game5: "Mario Kart 8 Deluxe",
  },
  {
    id: 26,
    abbreviation: "XBSX",
    gen: "9",
    manufacture: "Microsoft",
    system: "Xbox Series X/S",
    units: "6M",
    describe:
      "Starting the ninth generation of home consoles just as they had done previously",
    year: "2020",
    discontinued: "Present",
    price: "£249-£449",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "/src/images/xbsxs.png",
    game1: "Assassin's Creed Valhalla",
    game2: "Call of Duty: Black Ops Cold War",
    game3: "Madden NFL 21",
    game4: "NBA 2K21",
    game5: "Dirt 5",
  },
  {
    id: 27,
    abbreviation: "PS5",
    gen: "9",
    manufacture: "Sony",
    system: "PlayStation 5",
    units: "32M",
    describe: "The latest cutting edge console from Sony.",
    year: "2020",
    discontinued: "Present",
    price: "£359-£449",
    icon: <VideogameAssetRoundedIcon />,
    image:
      "https://static.wikia.nocookie.net/sonic/images/3/30/PlayStation_5.png",
    game1: "Spider-Man: Miles Morales",
    game2: "Call of Duty: Black Ops Cold War",
    game3: "Assassin's Creed Valhalla",
    game4: "Demon's Souls",
    game5: "NBA 2K21",
  },
];

export default Data;
